export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_COMPLETE = "REGISTER_COMPLETE";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_COMPLETE = "LOGIN_USER_COMPLETE";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_COMPLETE = "UPDATE_USER_COMPLETE";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_COMPLETE = "LOGOUT_USER";
export const CREATE_TODO_ERROR = "CREATE_TODO_ERROR";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_COMPLETED = "GET_TODOS_COMPLETED";

export const SET_EDIT_TODO = "SET_EDIT_TODO";

export const EDIT_TODO = "EDIT_TODO";
export const EDIT_TODO_COMPLETE = "EDIT_TODO_COMPLETE";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";
